### ISSUE TITLE
[REVIEW] Authorship

### ISSUE THREAD

**Issue by FranjoIM** [ahoshiyar/ordPens#4]
In the acknowledgments of the paper, you mention JG created initial versions of the package and FS implemented ordinal smoothing penalty functionality, it might be appropriate to list them as co-authors on the manuscript. This is to discretion of (potential) authors and editor.

**Comment by ahoshiyar** [comment]
Thank you for the advice. I've contacted the previous contributors regarding co-authorship. They refrain from being mentioned as co-autors in the JOSS paper.

**Comment by FranjoIM** [comment]
Understood. Thank you!
