### ISSUE TITLE
[REVIEW] Community guidelines

### ISSUE THREAD

**Issue by FranjoIM** [ahoshiyar/ordPens#5]
Please include clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support.

**Comment by ahoshiyar** [comment]
Thank you, communitiy guidelines regarding 1) contributing 2) reporting issues  3) seeking support have been added to the ReadMe file. The file CONTRIBUTING.md has been added as well.

**Comment by FranjoIM** [comment]
Looks great. Thanks!
