### ISSUE TITLE
Code of Conduct and Contributing Guideline

### ISSUE THREAD

**Issue by mingzehuang** [ahoshiyar/ordPens#6]
Overall it looks great to see a package dealing with ordinal data without need to specify each cases (numbers of ordinal levels) specifically. I'm reading the detail, but for now I would suggest you adding some files like CODE OF CONDUCT and CONTRIBUTING GUIDELINE in line with many other packages published on JOSS. Thanks!

**Comment by ahoshiyar** [comment]
Thank you, communitiy guidelines regarding 1) contributing & code of conduct 2) reporting issues  3) seeking support have been added to the ReadMe file. The file CONTRIBUTING.md has been added as well.

**Comment by mingzehuang** [comment]
Looks nice! Thanks!
