### ISSUE TITLE
Installation guidance on README.md

### ISSUE THREAD

**Issue by mingzehuang** [ahoshiyar/ordPens#7]
It looks easy and smooth to install your package from GitHub. I would suggest you adding a code chunck in your README.md like
"devtools::install_git("https://github.com/ahoshiyar/ordPens", build_vignettes = TRUE)" to make it even more convenient the specification of "build_vignettes = TRUE" helps new users to get vignettes in correct way:)

**Comment by ahoshiyar** [comment]
Thank you for the advice! Installation instructions have been added to the README.md :)

**Comment by mingzehuang** [comment]
Seems great! Thanks!
