### ISSUE TITLE
Possible related methods

### ISSUE THREAD

**Issue by mingzehuang** [ahoshiyar/ordPens#8]
It's nice to use penalty term's to deal with ordinal data:) It's straightforward and solid in theory. I wonder if it's possible to compare penalty method with Gaussian copula model for latent correlation (of ordinal data) as the package we did before [latentcor](https://joss.theoj.org/papers/10.21105/joss.03634) ? Thanks!

**Comment by ahoshiyar** [comment]
Thank you for this interesting reference! Actually, the methods differ in their point of view. The latent Gaussian copula model has been cited in the paper.md now with a few notes on latent variables and potential future research.
However, I think a detailed discussion or comparison of the ordinal penalty & the latentcor would lie beyond the scope of the JOSS manuscript.

**Comment by mingzehuang** [comment]
Thank you for your reply, @ahoshiyar ! I definitely agree with you! And also many thinks for your citation! JOSS does focus on software rather than math foundation:) I was asking this question because we're doing related things and I want to hear your opinion about this:) Thank you for your comment:) Also I'm definitely fine with your math and code in "statement of need" part and "ordPens in action":) Since JOSS focus on software, I'm afraid that someone may have difficulty to understand what your math is doing at the beginning. A possible suggestion may be switching your order of two parts in "statement of need". First part you're going to explain there's no good package to address non-linearity and biasness caused by ordinal data in PCA even in IBM SPSS. (This reminds readers what you're going to do.) Then you go to your math:) But this is just my personal opinion. Overall it's definitely great explanation:)

**Comment by mingzehuang** [comment]
Looks great, thanks!
