### ISSUE TITLE
[REVIEW]reference details

### ISSUE THREAD

**Issue by fartist** [ahoshiyar/ordPens#9]
1.
 Huang, M., Müller, C. L., & Gaynanova, I. (2021). Latentcor: An r package for estimating
114 latent correlations from mixed data types. Journal of Open Source Software, 6(65), 3634.

"r" should be in uppercase.

2. line 7, add a couple of references for general statistical treatment for using regularization for ordinal variables.

3. line 70, why the "thresholds" is denoted as "latent"? they are just statistical parameters, I would suggest taking "(latent)" here to avoid confusion with the latent continuous variable.

**Comment by osorensen** [comment]
Thanks for pointing this out @fartist. A comment to @ahoshiyar is that the reference formatting can be fixed by adding curly braces {} around the R in the BibTeX reference, so it becomes {R}. Then it will appear as an uppercase R.

**Comment by ahoshiyar** [comment]
Thank you! 
1. Thanks, has been changed.
2. These are mentioned in line 21, but I added them also to line 7 now.
3. Thank you for pointing out, the "latent" has been removed.

**Comment by ahoshiyar** [comment]
Thank you @fartist ! :)

Thanks, has been changed.
These are mentioned in line 21, but I added them also to line 7 now.
Thank you for pointing out, the "latent" has been removed.
